### PR TITLE
Chapters 35-42

### PR DESCRIPTION
**Pull request by ThrawnCA**
Plus some capitalisation fixes in earlier chapters.

### CODE REVIEW

**Comment by IntermittentlyRupert** [comment]
Thanks for all this! I'll endeavour to add ch.43 tonight and do a release, unless you've got any typo fixes for that as well?

**Comment by ThrawnCA** [comment]
I put some in the viridian dreams forum thread.

**Comment by IntermittentlyRupert** [comment]
Possibly I'm being unobservant, but I can't find it. Can you please give me a link?

**Comment by ThrawnCA** [comment]
Oh, wait. That was the post that I lost when my session timed out. Eh, I'll get to it later.

**Comment by ThrawnCA** [comment]
true but it didn't/true, but it didn't

get out in front/get on top

snatched the wand from its holster - one of the pronouns should be "his"

one of a kind/one-of-a-kind

to protect for a thousand/to protect, for a thousand

left the hall but/left the hall, but

hear the oath I swore,/hear the oath I swore?

against Hogwarts so-called/against Hogwarts' so-called

demeanor/demeanour

Ginny! He reminded/Ginny! he reminded

honors/honours

OWLS and NEWTS/OWLs and NEWTs

covers everything, headmaster/covers everything, Headmaster

Madam Maxime/Madame Maxime
(occurs multiple times)

lead Fleur from/led Fleur from

McClaggen/McLaggen

boys room/boys' room

bordering with/bordered with

practicing/practising
(occurs multiple times)

they make their way/they made their way

portrait Harry was/portrait, Harry was

H-harry/H-Harry

What is it Colin/What is it, Colin

your parents Harry/your parents, Harry

are we going Hermione/are we going, Hermione

Two weeks suspension/Two weeks' suspension

smile and began/smile, and began

"now be 'ounding Millie for a follow-up interview now" - Double 'now'

eying/eyeing

Mr. Potter I suppose/Mr. Potter, I suppose

didn't mind, what he had/didn't mind; what he had

the blonde's/the blond's

Madame Pomfrey/Madam Pomfrey

practiced/practised

and another chain appear/and another chain appeared

its limbs and when/its limbs, and when

ghastly, what was/ghastly; what was

The horntail/The Horntail

next and possibly last,/next, and possibly last,

the contestant's entrance/the contestants' entrance

directly at Harry and/directly at Harry, and

cracked the shell then/cracked the shell than

Harry snarked. "It's/Harry snarked, "it's

Victor Krum/Viktor Krum

blame her, she must/blame her; she must

"He pulled out" - This is a bit confusing since "he" in the previous sentence meant Snape. Perhaps "Who pulled out" would be better.

kill Harry second year,/kill Harry second year?

The elder Weasley asked/the elder Weasley asked

**Comment by IntermittentlyRupert** [comment]
Thanks, I'll do a point release tonight.

**Comment by ThrawnCA** [comment]
I can do a pull request for this if you want

**Comment by IntermittentlyRupert** [comment]
Nah, all good. I've got some free time this evening.

**Pull request merged**
